

# This file was *autogenerated* from the file mob.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_12 = Integer(12)
from random import randint
from itertools import product
from utils import index_of

def mob_transform(sol, vars):
    return _f_expand(_sage_const_0 , vars, sol)

def _f_expand(lvl, vars, sol):
    alt = lambda val : [val if lvl == idx else e for idx, e in enumerate(vars)]
    if lvl == len(vars):
        idx = index_of(vars)
        return sol[idx]
    else:
        tmp = _f_expand(lvl + _sage_const_1 , alt(_sage_const_0 ), sol)
        f1 = tmp + _f_expand(lvl + _sage_const_1 , alt(_sage_const_1 ), sol)
        f2 = tmp
        return vars[lvl] * f1 + f2

def mob_inv(poly):
    sol = dict()
    for idx, bits in enumerate(product([GF(_sage_const_2 )(_sage_const_0 ), GF(_sage_const_2 )(_sage_const_1 )], repeat=len(poly.args()))):
        sol[idx] = poly(*(bits[::-_sage_const_1 ]))
    return sol

def random_poly_GF2(R, degree):
    return R(GF(_sage_const_2 )[R.gens()].random_element(degree=degree))

def test_mob():
    for _ in range(_sage_const_1 ):
        num_vars = _sage_const_12  #randint(2,10)
        R = GF(_sage_const_2 )[", ".join(["x" + str(i) for i in range(num_vars)])]
        p = random_poly_GF2(R, _sage_const_2 )
        sol = mob_inv(p)
        p_anf = mob_transform(sol, R.gens())
        p_anf_sol = mob_inv(p_anf)
        if sol != p_anf_sol:
            print(f"p{p.args()} =", p)
            print(f"p_anf{p_anf.args()} =", p_anf)
            print(sol)
            print(p_anf_sol)
    print("Testing done")

def main():
    test_mob()

if __name__ == "__main__":
    main()

